<a href="https://colab.research.google.com/github/radwasafty-spec/IEEE-CS-DataScience-26/blob/main/learning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cafe_sales.csv to cafe_sales.csv

In [ ]:
import pandas as pd

df = pd.read_csv("cafe_sales.csv")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
df.drop_duplicates()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
df.drop(columns="Payment Method")

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,In-store,2023-06-11
...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,In-store,2023-11-07

In [ ]:
df["Item"].str.lstrip("C")

0          offee
1            ake
2          ookie
3          Salad
4          offee
          ...
9995       offee
9996         NaN
9997       offee
9998       ookie
9999    Sandwich
Name: Item, Length: 10000, dtype: object